### ISSUE TITLE
请问如何使用url_for

### ISSUE THREAD

**Issue by jinxx1** [Blackyukun/quiet#3]
在templates的模板中，我添加  {{url_for('xxxx'}}

出现错误
jinja2.exceptions.UndefinedError: 'url_for' is undefined

请问，如何在模板中使用url_for呢？

**Comment by yokonsan** [comment]
要在 jinja2 的模板中使用 flask 的 url_for() 函数，需要有一个应用上下文栈`appctx = _app_ctx_stack.top`

本项目中，在调用 generate.py 生成 html 静态文件时，并未定义 flask 应用实例，所以他会抛出 `'url_for' is undefined` 的错误

要想在模板中使用该函数，需要在应用的上下文中调用。这样先生成静态文件的程序中，可以把静态文件目录作为变量`static_root`传给模板的占位符中`{{ static_root }}`
